### ISSUE TITLE
How can I train a new model based on your npy file？

### ISSUE THREAD

**Issue by kevisminename** [hjptriplebee/VGG19_with_tensorflow#2]
hello, i‘m a new learner on vgg net and happened to find your work, it's nice and easy, but now i have some of my own pictures, how can i train the net with mine pictures, and get my own model?

**Comment by hjptriplebee** [comment]
@kevisminename  It's just a practice on building network, I didn't write train code at that time. However, the code of training is easy to write. You just need to add a loss function, a train operation and some connectivity code. Of course, you will need to change your data to TFRecord format, if you expect to have a high speed.
